person:
  userName: zhangsan
  boss: true
  birth: 2021/03/20
  age: 18
  interests: [篮球,足球]
  animal: [猫,狗]
  score: {english:80,math:90}
  salarys:
    - 9999.98
    - 9999.99
  pet:
    name: 狗子
    weight: 99.99
  allPets:
    sick:
      - {name: 阿狗,weight: 99.99}
      - name: 阿猫
        weight: 88.88
      - name: 阿虫
        weight: 77.77
    health:
      - {name: 阿花,weight: 99.99}
      - {name: 阿明,weight: 99.99}



