#spring:
#  mvc:
#    static-path-pattern: /res/**

#  web:
#    resources:
#      static-locations: classpath:/haha/
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true
  #  mvc:
  #    static-path-pattern: /res/**


server:
        servlet:
          context-path: /world